### PR TITLE
Be more permissive when parsing Video field

### PR DESCRIPTION
**Pull request by jsbejeau**
This PR allow to do not systematically reject a bid_request which does not contain a complete set of field for Video Object.

### CODE REVIEW

**Comment by RAttab** [comment]
Just to confirm, with this change we're diverging from the OpenRTB standard where the mimes field is marked as required (it's like one of 4 fields that is) and this is something we're happy to do?

**Comment by oktal** [comment]
If we want to stay compliant with the spec, I would make two versions of the parser: one strict that strictly enforces the spec and one tolerent that would allow some fields missing and would try to put default values instead.

**Comment by marksweiss** [comment]
What is the motiviation for diverging from the spec?

**Comment by jsbejeau** [comment]
The goal here is to be more permissive when we received a bid_request. Actually, no one strictly respect the OpenRTB specification; so to avoid having to do some specific code by exchange connector, we could use values that we know it is "unspecified" by the exchange and allow us to use these datas in the training.

**Comment by RAttab** [comment]
Alrighty, was just making sure we knew we were diverging. Note that rtbd may need to be updated accordingly since the goiab can run a bunch of checks on the bid request and that requirement is part of those checks.

**Pull request merged**
